FROM node:14.17.5-alpine3.14 as build-stage

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.20.1-alpine
RUN addgroup app && adduser -S -G app app
USER app
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ] 